"use client"

import { Constants } from "@/app/utils/util";
import { auth } from "@/app/utils/firebase_client";
import { isSignInWithEmailLink, signInWithEmailLink } from "firebase/auth";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import AdminLogin from "@/app/admin/(login)/pages/admin-login";
import NotAnAdminPage from "@/app/admin/(login)/pages/not-an-admin";
import { FirebaseError } from "firebase/app";
import { adminLogin, isAdmin } from "@/app/utils/login";
import { toast } from "sonner";
import { ArrowPathIcon } from "@heroicons/react/24/solid";

export default function AdminPage() {
	const router = useRouter();

	const [state, setState] = useState<"loading" | "login" | "not-an-admin">("loading");

	useEffect(() => {
		let mounted = true;

		const run = async () => {
			const url = window.location.href;
			const email = localStorage.getItem(Constants.EMAIL_LOCALSTORAGE_KEY);

			await auth.authStateReady();
			if (!mounted) return;

			const user = auth.currentUser;
			// Checks to see if url is the redirect url generated by Firebase
			if (email && url && isSignInWithEmailLink(auth, url)) {
				try {
					const result = await signInWithEmailLink(auth, email, url);
					// Email was stored in localStorage
					localStorage.removeItem(Constants.EMAIL_LOCALSTORAGE_KEY);

					const idToken = await result.user.getIdToken();
					try {
						const loginSuccessful = await adminLogin(idToken);
						if (loginSuccessful) {
							router.replace("/admin/requests");
						} else {
							auth.signOut();
							if (mounted) setState("not-an-admin");
						}
					} catch (e) {
						if (e instanceof FirebaseError) {
							throw e; // Handled by outer catch
						} else {
							auth.signOut();
							if (mounted) setState("login");
						}
					}
				} catch (e) {
					console.log("Some error occurred: " + e);
					toast.error("Invalid or expired login link.");
				}
				// If user is already logged in and is an admin
			} else if (user && await isAdmin()) {
				router.replace("/admin/requests");
				// User is not logged in and was not redirected here
			} else {
				if (mounted) setState("login");
			}
		};

		run();

		// Called when the component is unmounted
		return () => {
			mounted = false;
		};
	}, [router]);

	if (state === "not-an-admin") {
		return <NotAnAdminPage />;
	} else if (state === "login") {
		return <AdminLogin />;
	} else {
		return <ArrowPathIcon width={32} height={32} className="animate-spin mx-auto" />
	}
}
